version: '3.8'

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=solita_assignment
    ports:
      - 3306:3306
    healthcheck:
      test: curl --fail http://localhost:3306 || exit 1
      interval: 10s
      retries: 5
      timeout: 5s
      
  assignment_backend:
    build: .
    depends_on:
      mysqldb:
        condition: service_healthy
    ports:
      - 3001:3001
    environment:
      - MYSQL_HOST_IP=mysqldb
      - DB_HOST=mysqldb
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=solita_assigngment
      - DB_PORT=3306
    stdin_open: true
    tty: true
